server:
  port: 8761


eureka:
  server:
    enable-self-preservation: false # \u5173\u95ED\u81EA\u6211\u4FDD\u62A4\u6A21\u5F0F\uFF08\u7F3A\u7701\u4E3A\u6253\u5F00\uFF09
    eviction-interval-timer-in-ms: 1000 # \u626B\u63CF\u5931\u6548\u670D\u52A1\u7684\u95F4\u9694\u65F6\u95F4\uFF08\u7F3A\u7701\u4E3A60*1000ms\uFF09
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false # \u662F\u5426\u6CE8\u518C\u81EA\u5DF1\u7684\u4FE1\u606F\u5230EurekaServer\uFF0C\u9ED8\u8BA4\u662Ftrue
    fetch-registry: false # \u662F\u5426\u62C9\u53D6\u5176\u5B83\u670D\u52A1\u7684\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u662Ftrue
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/